import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'es';

type TranslationValues = Record<string, string | number>;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string, values?: TranslationValues) => string;
};

const english: Record<string, string> = {
  'Arquitectura Monolito Modular • 5 Servicios de Dominio': 'Modular Monolith Architecture • 5 Domain Services',
  'Plataforma E-Commerce Modular': 'Modular E-Commerce Platform',
  'Interfaz desacoplada en React y Tailwind CSS conectada a los servicios independientes de': 'A decoupled React and Tailwind CSS interface connected to the independent services:',
  'Ver detalles del módulo Auth': 'View Auth module details',
  'Ver detalles del módulo Users': 'View Users module details',
  'Ver detalles del módulo Products': 'View Products module details',
  'Ver detalles del módulo Orders': 'View Orders module details',
  'Ver detalles del módulo Payments': 'View Payments module details',
  'Lucide Icons para simbología técnica': 'Lucide Icons for technical iconography',
  'Av. Paseo 1234, Depto 4': 'Paseo Avenue 1234, Apt. 4',
  'Madrid': 'Madrid',
  'JWT & Sesión': 'JWT & Session',
  'Perfiles & Direcciones': 'Profiles & Addresses',
  'Stock & Catálogo': 'Inventory & Catalog',
  'Carrito & Estados': 'Cart & Statuses',
  'Cobros & Pasarelas': 'Charges & Gateways',
  'Monolito API Inspector': 'Monolith API Inspector',
  'MODULAR': 'MTRADE',
  '.STORE': ' APP',
  'Plataforma de comercio electrónico basada en arquitectura de monolito modular con 5 servicios integrados: Auth, Users, Products, Orders y Payments.': 'An e-commerce platform built on a modular monolith with five integrated services: Auth, Users, Products, Orders, and Payments.',
  'Servicios del Monolito': 'Monolith Services',
  'Users Service (Gestión de perfiles)': 'Users Service (Profile management)',
  'Products Service (Catálogo e inventario)': 'Products Service (Catalog and inventory)',
  'Orders Service (Máquina de estados de pedidos)': 'Orders Service (Order state machine)',
  'Payments Service (Pasarelas y cobros)': 'Payments Service (Gateways and charges)',
  'Pila Tecnológica Frontend': 'Frontend Stack',
  'Inspector de telemetría HTTP en tiempo real': 'Real-time HTTP telemetry inspector',
  'Garantía & Seguridad': 'Warranty & Security',
  'Manejo transaccional atómico con reserva de inventario previa a la confirmación de pago y emisión de comprobantes digitales.': 'Atomic transaction handling with inventory reserved before payment confirmation and digital receipt generation.',
  '© 2026 Modular E-Commerce Platform. Diseñado con React y Tailwind CSS.': '© 2026 MTrade App. Built with React and Tailwind CSS.',
  '5 Servicios Activos': '5 Active Services',
  '100% Sin Errores': '100% Error-Free',
  'Abrir Inspector': 'Open Inspector',
  'Monolito Modular Backend: 5 Servicios (auth • users • products • orders • payments)': 'Modular Monolith Backend: 5 Services (auth • users • products • orders • payments)',
  'Abrir Inspector de Servicios Monolito': 'Open Monolith Services Inspector',
  'Inspector de API ({count} reqs)': 'API Inspector ({count} reqs)',
  'Modular Monolith Platform': 'Modular Commerce Platform',
  'Buscar productos por nombre, categoría o SKU...': 'Search products by name, category, or SKU...',
  'Buscar productos...': 'Search products...',
  'tu@correo.com': 'you@example.com',
  'Agregar producto al catálogo': 'Add product to catalog',
  'Agregar producto': 'Add product',
  'Ver mis pedidos creados en Orders Service': 'View my orders from Orders Service',
  'Mis Pedidos': 'My Orders',
  'Carrito': 'Cart',
  'Abrir Carrito': 'Open Cart',
  'Rol: {role}': 'Role: {role}',
  'Mi Perfil y Direcciones': 'My Profile & Addresses',
  'Historial de Pedidos': 'Order History',
  'Cerrar Sesión (Auth Service)': 'Sign Out (Auth Service)',
  'Ingresar': 'Sign In',
  'Solo en stock': 'In stock only',
  'Mejor Calificados': 'Top Rated',
  'Precio: Menor a Mayor': 'Price: Low to High',
  'Precio: Mayor a Menor': 'Price: High to Low',
  'Mostrando': 'Showing',
  'productos': 'products',
  'para la búsqueda': 'for search',
  'No se encontraron productos': 'No products found',
  'Todos': 'All',
  'Intenta cambiar los términos de búsqueda o restablecer los filtros para ver todos los artículos del catálogo.': 'Try changing your search or resetting the filters to see all catalog items.',
  'Restablecer Filtros': 'Reset Filters',
  'Destacado': 'Featured',
  'Vista Rápida': 'Quick View',
  'Agotado': 'Out of stock',
  '¡Últimas {count} unids!': 'Only {count} left!',
  'Stock: {count}': 'Stock: {count}',
  'Agregado': 'Added',
  'Añadir': 'Add',
  'OFERTA': 'SALE',
  '({count} opiniones verificadas)': '({count} verified reviews)',
  'Stock disponible:': 'Available stock:',
  'unids.': 'units',
  'Envío seguro y express': 'Safe, express shipping',
  'Garantía de 12 meses': '12-month warranty',
  'Cantidad:': 'Quantity:',
  'Agregado al Carrito': 'Added to Cart',
  'Añadir al Carrito': 'Add to Cart',
  'Comprar Ahora': 'Buy Now',
  'Carrito de Compras': 'Shopping Cart',
  'ítem': 'item',
  'ítems': 'items',
  'Agrega {amount} para Envío Gratis': 'Add {amount} more for free shipping',
  '¡Felicidades! Calificas para Envío Gratis a domicilio': 'Congratulations! You qualify for free home delivery',
  'Tu carrito está vacío': 'Your cart is empty',
  'Explora nuestro catálogo con productos de alta tecnología y añade lo que te guste.': 'Explore our catalog of tech products and add something you like.',
  'Continuar Comprando': 'Continue Shopping',
  'Eliminar artículo': 'Remove item',
  'Envío estimado': 'Estimated shipping',
  'GRATIS': 'FREE',
  'Impuestos (21% IVA)': 'Taxes (21% VAT)',
  'Total Final': 'Order Total',
  'Proceder al Pago': 'Proceed to Checkout',
  'Conexión segura coordinada por Orders & Payments Services': 'Secure checkout coordinated by Orders & Payments Services',
  'Checkout Seguro Monolito': 'Secure Monolith Checkout',
  'Envío (Users)': 'Shipping (Users)',
  'Pago (Payments)': 'Payment (Payments)',
  'Confirmación (Orders)': 'Confirmation (Orders)',
  'Por favor ingresa la calle y ciudad de entrega.': 'Please enter the delivery street and city.',
  'Dirección de Entrega (Users Service)': 'Shipping Address (Users Service)',
  'Usar dirección guardada': 'Use saved address',
  '+ Nueva dirección': '+ New address',
  'Predeterminada': 'Default',
  'Nombre o Etiqueta:': 'Name or Label:',
  'Ej: Casa, Oficina, Departamento': 'e.g. Home, Office, Apartment',
  'Calle y Número:': 'Street and Number:',
  'Ciudad:': 'City:',
  'Código Postal:': 'ZIP / Postal Code:',
  'Artículos en la orden:': 'Items in order:',
  'Total estimado con envío e IVA:': 'Estimated total with shipping and VAT:',
  'Continuar a Pago': 'Continue to Payment',
  'Método de Pago (Payments Service)': 'Payment Method (Payments Service)',
  'Tarjeta Crédito': 'Credit Card',
  'Transferencia': 'Bank Transfer',
  'Número de Tarjeta:': 'Card Number:',
  'Titular:': 'Cardholder:',
  'Vence:': 'Expires:',
  'Impuestos (21% IVA):': 'Taxes (21% VAT):',
  'Subtotal productos:': 'Items subtotal:',
  'Coste de envío:': 'Shipping cost:',
  'Gratis': 'Free',
  'Total a Cobrar:': 'Amount Due:',
  'Volver a Envío': 'Back to Shipping',
  'Autorizar y Pagar ${amount}': 'Authorize and Pay ${amount}',
  'Conexión con cuenta PayPal:': 'Connect to PayPal account:',
  'Se autorizará un débito instantáneo de': 'An instant charge of',
  'mediante el token de sesión de Payments Service.': 'will be authorized using the Payments Service session token.',
  'Transferencia Instantánea SEPA / Red Bancaria:': 'Instant SEPA / Bank Network Transfer:',
  'El servicio de pagos emitirá una confirmación digital inmediata con código de autorización bancario.': 'The payment service will issue an immediate digital confirmation with a bank authorization code.',
  'Coordinando Monolito Modular...': 'Coordinating the modular monolith...',
  '1. Users Service: validando cuenta...': '1. Users Service: validating account...',
  '2. Orders Service: instanciando orden...': '2. Orders Service: creating order...',
  '3. Payments Service: procesando cargo...': '3. Payments Service: processing charge...',
  '4. Products Service: reservando inventario...': '4. Products Service: reserving inventory...',
  '¡Orden Confirmada con Éxito!': 'Order Confirmed Successfully!',
  'Procesada por los 5 servicios del Monolito Modular': 'Processed by all 5 modular monolith services',
  'Nº de Orden:': 'Order No.:',
  'Estado: {status}': 'Status: {status}',
  'Código de Autorización:': 'Authorization Code:',
  'Método de Pago:': 'Payment Method:',
  'Dirección de Envío:': 'Shipping Address:',
  'Productos adquiridos:': 'Items purchased:',
  'Monto Total Cobrado:': 'Total Charged:',
  'Regresar a la Tienda': 'Return to Store',
  'Historial de Pedidos (Orders Service)': 'Order History (Orders Service)',
  'Recargar órdenes': 'Refresh orders',
  'Cargando pedidos desde Orders Service...': 'Loading orders from Orders Service...',
  'No tienes pedidos registrados': 'You have no orders yet',
  'Realiza una compra para ver el seguimiento en tiempo real entre Orders y Payments.': 'Place an order to track it across Orders and Payments in real time.',
  'Pagado': 'Paid',
  'En Camino': 'On the way',
  'Entregado': 'Delivered',
  'Procesando': 'Processing',
  'Pendiente': 'Pending',
  'artículos': 'items',
  'Detalles de Orden': 'Order Details',
  'Estado del Envío y Entrega:': 'Shipping and Delivery Status:',
  '✓ Recibido': '✓ Received',
  '✓ Pagado': '✓ Paid',
  '● En Tránsito': '● In Transit',
  '● Entregado': '● Delivered',
  'Nº de Seguimiento:': 'Tracking No.:',
  'Artículos del Pedido:': 'Order Items:',
  'Destino:': 'Destination:',
  'Pago:': 'Payment:',
  'Tarjeta Verificada': 'Verified Card',
  'Total Pagado:': 'Total Paid:',
  'Selecciona una orden de la lista': 'Select an order from the list',
  'Mi Perfil y Cuenta (Users Service)': 'My Profile & Account (Users Service)',
  'Perfil actualizado correctamente en Users Service.': 'Profile updated successfully in Users Service.',
  'Nueva dirección registrada en Users Service.': 'New address saved in Users Service.',
  'Rol:': 'Role:',
  'Cancelar': 'Cancel',
  'Editar Datos': 'Edit Details',
  'Nombre Completo:': 'Full Name:',
  'Teléfono Móvil:': 'Mobile Phone:',
  'Guardar Cambios (PUT /api/users/{id})': 'Save Changes (PUT /api/users/{id})',
  'Libreta de Direcciones (Users Service)': 'Address Book (Users Service)',
  'Cerrar Formulario': 'Close Form',
  'Agregar Dirección': 'Add Address',
  'Etiqueta:': 'Label:',
  'Dirección / Calle:': 'Address / Street:',
  'País:': 'Country:',
  'Principal': 'Primary',
  'No hay direcciones registradas.': 'No addresses saved.',
  'Auth Service JWT Token:': 'Auth Service JWT Token:',
  'Alternar cuenta de prueba:': 'Switch demo account:',
  'Cliente (Camila)': 'Customer (Camila)',
  'Admin (Plataforma)': 'Admin (Platform)',
  'Ingresa un correo electrónico.': 'Enter an email address.',
  'Completa tu correo y contraseña.': 'Enter your email and password.',
  'Error en Auth Service': 'Auth Service error',
  'Iniciar Sesión (Auth Service)': 'Sign In (Auth Service)',
  'Crear Cuenta (Auth Service)': 'Create Account (Auth Service)',
  'Registrarse': 'Create Account',
  'Nombre:': 'First Name:',
  'Apellido:': 'Last Name:',
  'Correo Electrónico:': 'Email Address:',
  'Contraseña:': 'Password:',
  'Crear Cuenta': 'Create Account',
  'ACCESO RÁPIDO CON CUENTAS DEMO:': 'QUICK ACCESS WITH DEMO ACCOUNTS:',
  'Rol: Cliente': 'Role: Customer',
  'Rol: Administrador': 'Role: Administrator',
  'Completa nombre, precio válido y stock entero no negativo.': 'Enter a name, valid price, and non-negative whole-number stock.',
  'No se pudo crear el producto.': 'Could not create product.',
  'Cerrar': 'Close',
  'Nombre *': 'Name *',
  'Descripción': 'Description',
  'Precio *': 'Price *',
  'Stock *': 'Stock *',
  'Categoría': 'Category',
  'Imagen': 'Image',
  'Etiquetas': 'Tags',
  'hogar, nuevo, oferta': 'home, new, sale',
  'Guardando...': 'Saving...',
  'Crear producto': 'Create Product',
  'Operativo': 'Operational',
  'endpoints mapeados • Prefijo: /api/{service}/*': 'endpoints mapped • Prefix: /api/{service}/*',
  'Ver Logs': 'View Logs',
  'Feed de Solicitudes ({count})': 'Request Feed ({count})',
  'Mapa de Arquitectura (5 Módulos)': 'Architecture Map (5 Modules)',
  'Estructura del Monolito Modular': 'Modular Monolith Structure',
  'A diferencia de los microservicios distribuidos, el monolito modular ejecuta los 5 dominios de negocio en una sola base de código desplegable, manteniendo fronteras lógicas y modelos de dominio estrictamente desacoplados.': 'Unlike distributed microservices, a modular monolith runs all five business domains in one deployable codebase while maintaining clear boundaries and decoupled domain models.',
  'Flujo de Comunicación Típico:': 'Typical Communication Flow:',
  'Deducción de stock': 'Deduct inventory',
  'Actualización de estado a \'paid\'': 'Update status to \'paid\'',
  'Todos ({count})': 'All ({count})',
  'Limpiar logs': 'Clear logs',
  'No hay llamadas registradas para este filtro.': 'No calls recorded for this filter.',
  'Interactúa con la tienda (añade productos, navega, haz checkout) para ver tráfico en tiempo real.': 'Use the store (add products, browse, or check out) to see live traffic.',
  'Payload de Solicitud (Request):': 'Request Payload:',
  'Respuesta del Módulo (Response):': 'Module Response:',
  'Monolito Modular Backend Inspector': 'Modular Monolith Backend Inspector',
  '5/5 Servicios Activos': '5/5 Services Active',
  'Supervisa las llamadas HTTP y límites entre módulos (auth, users, products, orders, payments)': 'Monitor HTTP calls and module boundaries (auth, users, products, orders, payments)',
  'Autenticación JWT, control de sesiones, emisión y verificación de tokens.': 'JWT authentication, session management, and token issuance and verification.',
  'Perfiles de usuario, libretas de direcciones y configuración de clientes.': 'User profiles, address books, and customer settings.',
  'Catálogo de productos, control de stock en tiempo real, categorías y búsqueda.': 'Product catalog, real-time inventory, categories, and search.',
  'Gestión de carritos, creación y ciclo de vida de órdenes, tracking y estados.': 'Cart management, order creation and lifecycle, tracking, and status.',
  'Procesamiento de pagos, pasarelas de tarjetas, webhooks y generación de comprobantes.': 'Payment processing, card gateways, webhooks, and receipt generation.',
  'MTrade App': 'MTrade App',
  'React 19 con TypeScript': 'React 19 with TypeScript',
  'Tailwind CSS moderno': 'Modern Tailwind CSS',
  'Ocurrió un error al procesar la orden en los servicios.': 'An error occurred while processing the order.',
  'Ej: Apartamento Playa': 'e.g. Beach Apartment',
  'Calle Marina 45, Puerta 2': 'Marina Street 45, Unit 2',
  'Nueva Dirección': 'New Address',
  'Titular': 'Cardholder',
  'Tarjeta de Crédito (Visa •••• 4242)': 'Credit Card (Visa •••• 4242)',
  'Transferencia Bancaria': 'Bank Transfer',
  'Language': 'Language',
};

const spanish: Record<string, string> = {
  'Language': 'Idioma',
  'Buscar productos por nombre, categoría o SKU...': 'Buscar productos por nombre, categoría o SKU...',
  'Buscar productos...': 'Buscar productos...',
  'Products Service: 200 OK': 'Servicio de productos: 200 OK',
  '© 2026 Modular E-Commerce Platform. Diseñado con React y Tailwind CSS.': '© 2026 MTrade App. Hecha con React y Tailwind CSS.',
  'Modular Monolith Platform': 'Plataforma de Monolito Modular',
  'Safe, express shipping': 'Envío seguro y exprés',
  'Top Rated': 'Mejor valorados',
  'All': 'Todos',
  'English': 'Inglés',
  'and': 'y',
  'React 19 with TypeScript': 'React 19 con TypeScript',
  'Modern Tailwind CSS': 'Tailwind CSS moderno',
  'New Address': 'Nueva Dirección',
  'Cardholder': 'Titular',
  'Credit Card (Visa •••• 4242)': 'Tarjeta de Crédito (Visa •••• 4242)',
  'Bank Transfer': 'Transferencia Bancaria',
  'you@example.com': 'tu@correo.com',
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider: React.FC<React.PropsWithChildren> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() =>
    localStorage.getItem('mtrade-language') === 'es' ? 'es' : 'en',
  );

  useEffect(() => {
    localStorage.setItem('mtrade-language', language);
    document.documentElement.lang = language;
    document.title = 'MTrade App';
  }, [language]);

  const setLanguage = (nextLanguage: Language) => setLanguageState(nextLanguage);
  const t = (text: string, values: TranslationValues = {}) => {
    let translated = language === 'en' ? english[text] ?? text : spanish[text] ?? text;
    Object.entries(values).forEach(([key, value]) => {
      translated = translated.replaceAll(`{${key}}`, String(value));
    });
    return translated;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};